# Site settings
title: Thought Experiment
shortDescription: Ideacrafting For a Better World
email: rizky.farhan@live.com.au
description: > # this means to ignore newlines until "baseurl:"
  Ideas, if not  realized, are nothing but air. I have spent years jotting down my ideas in my trusty scrapbook.
  I want to share with the world ideas that are worth sharing, starting from my own.
  Writing these ideas on Github is one step closer to their reality.
  I will not abandon my scrapbook.
baseurl: "/thought-experiment"  # the subpath of your site, e.g. /blog/
#url: "https://rizkylearns.github.io/thought-experiment/" # the base hostname & protocol for your site
url: "https://rizkylearns.github.io" # the base hostname & protocol for your site
twitter_username: whatrizkydo 
github_username: rizkyLearns 

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "/thought-experiment/page:num"

author: Rizky Farhan

gems: [jekyll-paginate]
